### ISSUE TITLE
Update Microbe-ID with new functions and update (with Alex)

### ISSUE THREAD

**Issue by Tabima** [grunwaldlab/Microbe-ID#2]
After Alex joins the organization/team, she will be able to pull/push her changes to the repository, and we can fix the help pages, re-run each of the alignments and test the site before putting it live.

_The latest version of the site (with the merged code from Alex is *NOT_ live, as we are in the current version of testing.

**Comment by Tabima** [comment]
MLST integration using Alex's improvements are integrated to Microbe-ID :)

**Comment by grunwald** [comment]
Cool. Is this described in the paper, too?

Nik
